### ISSUE TITLE
Body parts will be invisible with HatchlingOutfitter

### ISSUE THREAD

**Issue by Owen013** [xen-42/ow-common-camera-util#6]
Example: head will be invisible if "Helmet" is set to "Always Off" while the player is wearing the suit. The same happens if helmet is set to always on and the player is unsuited. ~~This applies to the arms and body as well.~~ No it doesn't, only the head

![Outer Wilds Screenshot 2023 04 06 - 18 04 29 46](https://user-images.githubusercontent.com/96493201/230502688-261eb1f0-42c3-4d5f-826a-cf6673db71eb.png)
![Outer Wilds Screenshot 2023 04 06 - 18 04 42 72](https://user-images.githubusercontent.com/96493201/230502692-ddb62771-275c-481c-9750-f98d1093d497.png)

**Comment by xen-42** [comment]
Fixed in 1.3.1
